name: mirror-sync

on:
  schedule:
    - cron:  '12 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  mirror-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gautamkrishnar/keepalive-workflow@v1

    - name: dayzdockerserver
      if: ${{ always() }}
      run: ./mirror.sh
      env:
        source_repo: https://ceregatti.org/git/daniel/dayzdockerserver.git
        github_repo: dayzdockerserver.git
        branch: main
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: DayZ-CommunityFramework
      if: ${{ always() }}
      run: ./mirror.sh
      env:
        source_repo: https://github.com/Arkensor/DayZ-CommunityFramework.git
        github_repo: DayZ-CommunityFramework.git
        branch: production, development
        access_token: ${{ secrets.ACCESS_TOKEN }}

    - name: Pripyat Mission Files
      if: ${{ always() }}
      run: ./mirror.sh
      env:
        source_repo: https://github.com/FrenchiestFry15/PripyatMissionFiles.git
        github_repo: PripyatMissionFiles.git
        branch: main
        access_token: ${{ secrets.ACCESS_TOKEN }}
